---
title: "Take-home Exercise 1: Investigating Ship Performance with Data Visualization"
author: "Walaiporn Pawitranon"
execute: 
  warning: false
  echo: true
  eval: true
---

# 1. Overview

## 1.1 Background

The Ship Performance Dataset is a synthetic dataset that simulates real-world operational characteristics of different ship types operating in the Gulf of Guinea. The dataset contains detailed information on vessel operations, including ship type, engine type, route type, speed, fuel efficiency, cargo weight, operational cost, revenue, weather conditions, and voyage frequency. These variables together provide a comprehensive view of how maritime vessels perform under different operational and environmental conditions.

The maritime industry plays a crucial role in global trade, as the majority of goods are transported by sea. However, shipping operations are complex and influenced by multiple factors such as fuel technology, weather, route distance, and cargo load. Analysing ship performance data can help stakeholders better understand the trade-offs between cost, efficiency, and operational effectiveness, as well as identify opportunities for optimization and sustainability improvement.

Although the dataset is synthetically generated, it is designed to closely resemble real-world maritime scenarios. This makes it a useful resource for exploratory data analysis, visual analytics

## 1.2 The data

The dataset consists of 2736 rows and 24 columns, with features categorized into numerical and categorical types. Below are some key highlights:

#### Numerical Features

These capture performance metrics such as speed, power, cost, and energy efficiency, enabling detailed analysis and trend identification.

-   Speed_Over_Ground_knots: Average speed of the ship over water (in knots).

-   Engine_Power_kW: Engine power output (in kilowatts).

-   Distance_Traveled_nm: Total distance traveled by the ship (in nautical miles).

-   Operational_Cost_USD: Total operational cost per voyage (in USD).

-   Revenue_per_Voyage_USD: Revenue generated per voyage (in USD).

-   Efficiency_nm_per_kWh: Energy efficiency calculated in nautical miles per kilowatt-hour.

#### Categorical Features

Attributes such as ship type, route type, and weather conditions provide contextual insights and segmentation possibilities.

-   Ship_Type: Type of ship (e.g., Tanker, Container Ship, Fish Carrier, Bulk Carrier).

-   Route_Type: Shipping route type (e.g., Short-haul, Long-haul, Transoceanic).

-   Engine_Type: Type of engine (e.g., Diesel, Heavy Fuel Oil).

-   Maintenance_Status: Maintenance condition of the ship (e.g., Fair, Critical, Good).

-   Weather_Condition: Prevailing weather conditions during voyages (e.g., Calm, Moderate, Rough).

## 1.3 The task

# 2. Getting start

## 2.1 Loading packages

The following code chunk uses `p_load()` of [**pacman**](https://rpubs.com/akshaypatankar/594834) package to check if tidyverse packages are installed in the computer. If they are, the libraries will be called into R.

## 2.2 Data import

Ship_Performance_Dataset.csv will be used.

In the code chunk below, read_csv() of readr package is used to import Exam_data.csv into R and saved it into a tibble data.frame.

# 3. Data wrangling

## 3.1 Variables selection

## 3.2 Handling missing value

## 3.3 Recoding categorical variables

## 3.4 Data type conversion

## 3.5 Variable creation

# 4. Univariate Analysis

# 5. Exploratory Data Analysis

# 

# 6. Summary

# 

# 7. Reference

## 
